#version 460


layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) readonly uniform image2D inputImage;
layout(set = 0, binding = 1, rgba8) writeonly uniform image2D outputImage;

layout(push_constant) uniform PushConstants {
    vec2 direction;
    float sigma;
} pc;

const int MAX_RADIUS = 32;

float gaussianWeight(float x, float sigma) {
    float sigma2 = sigma * sigma;
    return exp(-(x*x)/(2.0*sigma2)) / (sqrt(2.0 * 3.14159265358979) * sigma);
}

void main() {
    ivec2 imgSize = imageSize(inputImage);
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);

    if(coord.x >= imgSize.x || coord.y >= imgSize.y) return;

    int radius = min(int(ceil(pc.sigma * 3.0)), MAX_RADIUS);

    vec4 colorSum = vec4(0.0);
    float weightSum = 0.0;

    for (int i = -radius; i <= radius; i++) {
        float w = gaussianWeight(float(i), pc.sigma);

        ivec2 sampleCoord = coord + ivec2(pc.direction * float(i));
        sampleCoord = clamp(sampleCoord, ivec2(0), imgSize - ivec2(1));

        colorSum += imageLoad(inputImage, sampleCoord) * w;
        weightSum += w;
    }

    imageStore(outputImage, coord, colorSum / weightSum);
}