#version 460

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform RayParams {
    vec3 origin;
    vec3 direction;
    float max_distance;
    uvec3 voxel_resolution;
} ray;

layout(set = 0, binding = 0, rgba32ui) readonly uniform uimage3D voxelImage;
layout(set = 1, binding = 0) buffer RaycastResult {
    uint hit;
    float distance;
} result;

bool readVoxel(uvec3 coord, inout uvec4 texel, inout ivec3 texel_coord) {
    ivec3 new_texel_coord = ivec3(coord.x / 4, coord.y / 4, coord.z / 8);

    if(new_texel_coord != texel_coord) {
        texel_coord = new_texel_coord;
        texel = imageLoad(voxelImage, texel_coord);
    } 
    return bool(texel[coord.x % 4] >> ((coord.y % 4) + (coord.z % 8) * 4) & 1u);
}

const float FLT_MAX = 3.4028235e+38;
const float EPSILON = 1e-4;

bool traversal(vec3 origin, vec3 dir, inout uint steps) {
    if(length(dir) < 1e-6) return false;

    vec3 res = vec3(ray.voxel_resolution);

    vec3 inv_dir = 1.0 / dir;
    vec3 sgn_dir = sign(dir);
    inv_dir = clamp(inv_dir, vec3(-FLT_MAX), vec3(FLT_MAX));

    vec3 t1 = -origin * inv_dir;
    vec3 t2 = (res - origin) * inv_dir;

    vec3 tmins = min(t1, t2);
    vec3 tmaxs = max(t1, t2);

    float tmin = 0.0;
    float tmax = FLT_MAX;
    for(int i = 0; i < 3; i++){
        tmin = max(tmin, tmins[i]);
        tmax = min(tmax, tmaxs[i]);
    }

    tmax = min(tmax, ray.max_distance);

    if(tmin > tmax) return false;

    uint stepped_axis;
    if (tmins.x < tmins.y){
        if(tmins.x < tmins.z) stepped_axis = 0;
        else stepped_axis = 2;
    } else {
        if(tmins.y < tmins.z) stepped_axis = 1;
        else stepped_axis = 2;
    }

    origin += dir * tmin;


    vec3 snapped = origin + EPSILON * dir;
    ivec3 icoord = ivec3(clamp(floor(snapped), vec3(0), res -1.0));
    ivec3 istep = ivec3(sgn_dir);
    vec3 t = (vec3(icoord) + 0.5 * (1.0 + sgn_dir) - origin) * inv_dir;
    t = max(t, vec3(0.0));
    vec3 delta = inv_dir * sgn_dir;

    uint max_steps = ray.voxel_resolution.x + ray.voxel_resolution.y + ray.voxel_resolution.z + 10u;

    ivec3 texel_coord = ivec3(-1);
    uvec4 texel = uvec4(0);

    bool instantHit = readVoxel(uvec3(icoord), texel, texel_coord);
    if(!instantHit)
    while (true) {
        steps++;
        if(steps > max_steps) return false;

        if(t.x < t.y){
            if(t.x < t.z) {
                icoord.x += istep.x;
                t.x += delta.x;
                stepped_axis = 0;
            } else {
                icoord.z += istep.z;
                t.z += delta.z;
                stepped_axis = 2;
            }
        } else {
            if(t.y < t.z) {
                icoord.y += istep.y;
                t.y += delta.y;
                stepped_axis = 1;
            } else {
                icoord.z += istep.z;
                t.z += delta.z;
                stepped_axis = 2;
            }
        }

        if (min(t.x, min(t.y, t.z)) > tmax) return false;

        if(any(lessThan(icoord, ivec3(0))) ||
        any(greaterThanEqual(icoord, ivec3(ray.voxel_resolution))))
        return false;

        if(readVoxel(uvec3(icoord), texel, texel_coord)) {
            result.distance = min(t.x, min(t.y, t.z));
            break;
        }
    }

    return true;
}

void main(){
    vec3 o = ray.origin;
    vec3 d = normalize(ray.direction);

    uint steps = 0;
    result.hit = traversal(o, d, steps) ? 1u : 0u;
}       